INFO:django.utils.autoreload:C:\Users\DELL\Desktop\messaging_app\messaging_app\messaging_app\settings.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\DELL\Desktop\messaging_app\messaging_app\chats\middleware.py changed, reloading.
INFO:root:2025-06-14 18:44:18.748802 - User: 7abd5f13-77c5-4150-bea8-ebab30611365 leticiaisoken@gmail.com) - Path: /api/messages/
ERROR:django.request:Internal Server Error: /api/messages/
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\DELL\Desktop\messaging_app\messaging_app\chats\views.py", line 26, in get_queryset
    return Message.objects.filter(conversation__particpants=self.request.user)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\db\models\sql\query.py", line 1563, in build_filter
    self.check_related_objects(join_info.final_field, value, join_info.opts)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\db\models\sql\query.py", line 1372, in check_related_objects
    self.check_query_object_type(value, opts, field)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\db\models\sql\query.py", line 1349, in check_query_object_type
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Cannot query "7abd5f13-77c5-4150-bea8-ebab30611365 leticiaisoken@gmail.com)": Must be "Conversation" instance.
INFO:root:2025-06-14 18:44:20.326738 - User: 7abd5f13-77c5-4150-bea8-ebab30611365 leticiaisoken@gmail.com) - Path: /api/messages/
ERROR:django.request:Internal Server Error: /api/messages/
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\DELL\Desktop\messaging_app\messaging_app\chats\views.py", line 26, in get_queryset
    return Message.objects.filter(conversation__particpants=self.request.user)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\db\models\sql\query.py", line 1563, in build_filter
    self.check_related_objects(join_info.final_field, value, join_info.opts)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\db\models\sql\query.py", line 1372, in check_related_objects
    self.check_query_object_type(value, opts, field)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\messaging_app\env\Lib\site-packages\django\db\models\sql\query.py", line 1349, in check_query_object_type
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Cannot query "7abd5f13-77c5-4150-bea8-ebab30611365 leticiaisoken@gmail.com)": Must be "Conversation" instance.
INFO:root:2025-06-14 18:44:20.592908 - User: 7abd5f13-77c5-4150-bea8-ebab30611365 leticiaisoken@gmail.com) - Path: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
INFO:root:2025-06-14 18:44:21.129110 - User: 7abd5f13-77c5-4150-bea8-ebab30611365 leticiaisoken@gmail.com) - Path: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
INFO:root:2025-06-14 18:44:23.712458 - User: 7abd5f13-77c5-4150-bea8-ebab30611365 leticiaisoken@gmail.com) - Path: /api/
INFO:root:2025-06-14 18:44:33.424284 - User: 7abd5f13-77c5-4150-bea8-ebab30611365 leticiaisoken@gmail.com) - Path: /api/
INFO:root:2025-06-14 18:44:37.594418 - User: 7abd5f13-77c5-4150-bea8-ebab30611365 leticiaisoken@gmail.com) - Path: /api/
INFO:root:2025-06-14 18:44:54.203201 - User: 7abd5f13-77c5-4150-bea8-ebab30611365 leticiaisoken@gmail.com) - Path: /api/conversations/
